name: CI

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Run first step
        run: echo Hello, world!
        
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Run second step
        run: echo Hello, world!
