name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: echo Build OK!

  stage:
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: stage
       url: https://stage.domain.com
    steps:
      - name: Deploy
        run: echo Deploy OK!
        
  production:
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: production
       url: https://prod.domain.com
    steps:
      - name: Deploy
        run: echo Deploy OK!
