name: Deploy

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: echo Hello, world!

  stage:
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: stage
       url: https://stage.domain.com
    steps:
      - name: Run first step
        run: echo Hello, world!
        
  production:
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: production
       url: https://prod.domain.com
    steps:
      - name: Run second step
        run: echo Hello, world!
