name: Run Bats tests

on:
  workflow_dispatch: 

jobs:
  test:
    name: Test Bast file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Bats tests
        uses: ffurrer2/bats-action@v1
        with:
          args: ./test.bats
